
(()=>{
function setupSite(){
 if(state.place!=='Coordinates')$('#year-place').value=state.place;
 const tooltip=document.createElement('div');tooltip.className='site-tooltip';tooltip.id='site-tooltip';tooltip.role='tooltip';tooltip.hidden=true;root.append(tooltip);
 function hide(){tooltip.hidden=true;all('[aria-describedby="site-tooltip"]').forEach(el=>el.removeAttribute('aria-describedby'));}
 function show(el){tooltip.textContent=el.dataset.tooltip;tooltip.hidden=false;el.setAttribute('aria-describedby','site-tooltip');const box=el.getBoundingClientRect();tooltip.style.left=Math.max(10,Math.min(innerWidth-tooltip.offsetWidth-10,box.left))+'px';tooltip.style.top=Math.max(10,box.top-tooltip.offsetHeight-9)+'px';}
 all('[data-tooltip]').forEach(el=>{el.addEventListener('pointerenter',()=>show(el));el.addEventListener('pointerleave',hide);el.addEventListener('focus',()=>show(el));el.addEventListener('blur',hide);el.addEventListener('click',()=>tooltip.hidden?show(el):hide());});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){hide();hideSuggestions();}});window.addEventListener('scroll',hide,{passive:true});document.addEventListener('click',e=>{if(!$('#year-name-form').contains(e.target))hideSuggestions();});
 $('#year-place').addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();suggest();$('#place-suggestions button')?.focus();}});
 $('#place-suggestions').addEventListener('keydown',e=>{const buttons=all('#place-suggestions button'),at=buttons.indexOf(document.activeElement);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();buttons[(at+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}});
 // Optional, feature-detected browser API. The same visible actions remain primary.
 if(document.modelContext?.registerTool){
  const lifetime=new AbortController();window.addEventListener('pagehide',()=>lifetime.abort(),{once:true});
  const tools=[{name:'read_map_value',description:'Read the PoFF probability of the selected grid box on the displayed day.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>snapshot()},{name:'select_archive_location',description:'Select coordinates in the PoFF archive and update the map.',inputSchema:{type:'object',properties:{latitude:{type:'number',minimum:-90,maximum:90},longitude:{type:'number',minimum:-180,maximum:180}},required:['latitude','longitude'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||Object.keys(input).some(k=>!['latitude','longitude'].includes(k))||!Number.isFinite(input.latitude)||!Number.isFinite(input.longitude)||Math.abs(input.latitude)>90||Math.abs(input.longitude)>180)throw new Error('Valid latitude and longitude are required.');choosePoint([input.longitude,input.latitude],'Coordinates');return snapshot();}}];
  for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifetime.signal})).catch(()=>{});}catch{}}
 }
}

const root=document.getElementById('atlas-year'),$=s=>root.querySelector(s),all=s=>[...root.querySelectorAll(s)];
const colours=['#ffffff','#8c8c8c','#f594c5','#ff007f','#73a3ff','#2500ff','#f5d98a','#c09313'],edges=[0,1,3,5,7,10,25,50,100],DAY=86400000;
const places={valencia:{label:'Valencia',region:'Valencian Community',country:'Spain',xy:[-.3763,39.4699]},valencia_ve:{label:'Valencia',region:'Carabobo',country:'Venezuela',xy:[-68.0077,10.162]},madrid:{label:'Madrid',region:'Community of Madrid',country:'Spain',xy:[-3.7038,40.4168]},barcelona:{label:'Barcelona',region:'Catalonia',country:'Spain',xy:[2.1734,41.3851]},lisbon:{label:'Lisbon',region:'Lisbon District',country:'Portugal',xy:[-9.1393,38.7223]},porto:{label:'Porto',region:'Porto District',country:'Portugal',xy:[-8.6291,41.1579]},seville:{label:'Seville',region:'Andalusia',country:'Spain',xy:[-5.9845,37.3891]},bilbao:{label:'Bilbao',region:'Basque Country',country:'Spain',xy:[-2.935,43.263]},algiers:{label:'Algiers',region:'Algiers Province',country:'Algeria',xy:[3.0588,36.7538]}};
const fullName=p=>`${p.label}, ${p.region}, ${p.country}`;
// One 32-bit colour (alpha, blue, green, red) per class of the raster; missing points are transparent.
const palette=Uint32Array.from([0,...colours.map(c=>(255<<24|parseInt(c.slice(5,7),16)<<16|parseInt(c.slice(3,5),16)<<8|parseInt(c.slice(1,3),16))>>>0)]);
const HOME={zoom:1,centre:[0,13.5]},MAX_ZOOM=64,PLACE_ZOOM=8;
const state={year:0,day:0,month:0,mapMode:'daily',point:[...places.valencia.xy],place:fullName(places.valencia),method:'name',threshold:5,metric:'mean',clicked:false,zoom:HOME.zoom,centre:[...HOME.centre],appearance:'auto',radius:8};
let start,dates,months,drag=null,raf=0,timer=null,currentCell=null,stats=null,seriesX,seriesY;
function calendar(y){const s=Date.UTC(y,0,1),n=(Date.UTC(y+1,0,1)-s)/DAY;return {start:s,dates:Array.from({length:n},(_,d)=>new Date(s+d*DAY)),months:Array.from({length:12},(_,m)=>({name:new Date(Date.UTC(y,m,1)).toLocaleDateString('en-GB',{month:'long',timeZone:'UTC'}),start:(Date.UTC(y,m,1)-s)/DAY,end:(Date.UTC(y,m+1,1)-s)/DAY}))};}

// The archive is what data/manifest.json lists: the page assumes nothing about its period or its grid.
// Each year is one file with, per day, the points at or above 1% and the land points without a value.
const archive={manifest:null,grid:null,world:null,land:null,years:new Map(),loaded:new Map(),problem:''};
// field: the map on display. open: the days of the selected year that are published.
let field=null,open=[],raster=null,hatch=null;
async function read(url,json=true){const r=await fetch(url);if(!r.ok)throw Error(`${url}: ${r.status}`);return json?r.json():r.arrayBuffer();}
async function unpack(bytes){if(typeof DecompressionStream!=='function')throw Error('DecompressionStream is not available');return new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer());}
// Only secure pages can compute digests; elsewhere the files are read unchecked.
async function digest(bytes){if(!globalThis.crypto?.subtle)return '';return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');}
// Reduced Gaussian grid: rows run from north to south; each row starts at 0° E and has its own number of points.
function makeGrid(g){const rows=g.points_per_row.length,offset=new Uint32Array(rows+1),edge=new Float64Array(rows+1);for(let r=0;r<rows;r++){offset[r+1]=offset[r]+g.points_per_row[r];edge[r]=r?(g.row_latitude[r-1]+g.row_latitude[r])/2:90;}edge[rows]=-90;if(g.type!=='reduced_gg'||g.row_latitude.length!==rows||offset[rows]!==g.points)throw Error('grid.json does not describe a reduced Gaussian grid');return {name:g.name,points:g.points,rows,offset,edge,count:Uint32Array.from(g.points_per_row),latitude:Float64Array.from(g.row_latitude),spacing:40075/Math.max(...g.points_per_row)};}
function wrap(lon){return ((lon+180)%360+360)%360-180;}
function rowAt(lat){const e=archive.grid.edge;let lo=0,hi=archive.grid.rows-1;while(lo<hi){const mid=(lo+hi)>>1;if(lat<e[mid+1])lo=mid+1;else hi=mid;}return lo;}
function cellAt(xy){const g=archive.grid;if(!g||!xy.every(Number.isFinite)||Math.abs(xy[1])>90)return null;const row=rowAt(xy[1]),n=g.count[row],col=Math.round(((xy[0]%360+360)%360)/360*n)%n;return {index:g.offset[row]+col,row,col,xy:[wrap(col*360/n),g.latitude[row]],width:360/n,north:g.edge[row],south:g.edge[row+1]};}
// Natural Earth cuts polygons at the antimeridian and closes Antarctica along the pole: those edges are not coastlines.
function outline(rings,coast=false){const path=new Path2D(),seam=(x,y)=>Math.abs(x)>=180||y<=-89.99;for(const r of rings){path.moveTo(r[0],-r[1]);for(let i=2;i<r.length;i+=2){if(coast&&seam(r[i],r[i+1])&&seam(r[i-2],r[i-1]))path.moveTo(r[i],-r[i+1]);else path.lineTo(r[i],-r[i+1]);}if(!coast)path.closePath();}return path;}
async function openArchive(){const [manifest,world]=await Promise.all([read('./data/manifest.json'),read('./world.json')]),e=manifest.encoding;if(manifest.format!==2||e.type!=='sparse-year'||e.compression!=='gzip'||!manifest.years.length)throw Error('manifest.json has a format that this page does not read');const [grid,land]=await Promise.all([read('./data/'+manifest.grid),verified('./data/'+manifest.land.file,manifest.land.sha256).then(unpack)]);archive.grid=makeGrid(grid);const n=archive.grid.points;if(land.length<n/8)throw Error('land.bin does not fit the grid');archive.land=new Uint8Array(n);for(let i=0;i<n;i++)archive.land[i]=land[i>>3]>>(i&7)&1;for(const y of manifest.years)archive.years.set(y.year,{...y,missing:new Set(y.missing)});archive.world={land:outline(world.land),lakes:outline(world.lakes),coast:outline(world.land,true)};archive.manifest=manifest;}
function firstDate(){const y=archive.manifest.years[0];return dateAfter(`${y.year}-01-01`,y.missing);}function lastDate(){const y=archive.manifest.years.at(-1);return dateAfter(`${y.year}-12-31`,y.missing,-1);}
function dateAfter(date,missing,step=1){while(missing.includes(date))date=new Date(Date.parse(date+'T00:00:00Z')+step*DAY).toISOString().slice(0,10);return date;}
async function verified(path,sha){const bytes=await read(path,false),sum=await digest(bytes);if(sum&&sum!==sha)throw Error(`${path} differs from the manifest`);return bytes;}
function cumulative(a){const out=new Uint32Array(a.length);let sum=0;for(let i=0;i<a.length;i++)out[i]=sum+=a[i];return out;}
// The layout is described in poff_web.py: a header, a table of the days, then the arrays of each day.
function parseYear(raw,year){const v=new DataView(raw.buffer,raw.byteOffset,raw.byteLength);if(raw.length<12||String.fromCharCode(...raw.subarray(0,4))!=='POFF'||v.getUint16(4,true)!==2||v.getUint16(6,true)!==year)throw Error(`maps/${year}.bin is not a year file of this format`);const n=v.getUint16(8,true),days=new Map();let at=12+12*n;for(let i=0;i<n;i++){const day=v.getUint16(12+12*i,true),kept=v.getUint32(16+12*i,true),lost=v.getUint32(20+12*i,true);const index=cumulative(new Uint32Array(raw.buffer,raw.byteOffset+at,kept));at+=4*kept;const code=new Uint16Array(raw.buffer,raw.byteOffset+at,kept);at+=2*kept+2*(kept%2);const unavailable=cumulative(new Uint32Array(raw.buffer,raw.byteOffset+at,lost));at+=4*lost;days.set(day,{index,code,unavailable});}if(at!==raw.byteLength)throw Error(`maps/${year}.bin has trailing bytes`);return days;}
function loadYear(year){if(!archive.loaded.has(year)){const entry=archive.years.get(year);archive.loaded.set(year,verified('./data/'+entry.file,entry.sha256).then(unpack).then(raw=>parseYear(raw,year)).catch(error=>{archive.loaded.delete(year);throw error;}));if(archive.loaded.size>4)archive.loaded.delete(archive.loaded.keys().next().value);}return archive.loaded.get(year);}
// The map of one day: class 0 is a point without a value, 1 is land below 1%, 2 to 8 are the intervals of the legend.
function fieldOf(days,date){const day=days.get((Date.parse(date+'T00:00:00Z')-start)/DAY);if(!day)return null;const e=archive.manifest.encoding,per=Math.round(1/e.scale),limits=edges.slice(1,-1).map(v=>Math.round(v*per)),classes=new Uint8Array(archive.land);for(const i of day.unavailable)classes[i]=0;for(let j=0;j<day.index.length;j++){let k=0;while(k<limits.length&&day.code[j]>=limits[k])k++;classes[day.index[j]]=k+1;}return {date,...day,classes,per,threshold:e.threshold};}
function hasSeries(){return !!archive.manifest?.series;}
function available(date){const entry=archive.years.get(+date.slice(0,4));return !!entry&&!entry.missing.has(date);}
function setYear(year){state.year=year;({start,dates,months}=calendar(year));open=[];dates.forEach((d,i)=>{if(available(d.toISOString().slice(0,10)))open.push(i);});state.day=nearest(state.day);}
function nearest(d){return open.reduce((a,b)=>Math.abs(b-d)<Math.abs(a-d)?b:a,open[0]);}
const ns='http://www.w3.org/2000/svg';function node(tag,attrs,parent){const n=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);parent.appendChild(n);return n;}
function fmtDay(i,long=false){return dates[Math.max(0,Math.min(dates.length-1,i))].toLocaleDateString('en-GB',{day:'numeric',month:long?'long':'short',year:'numeric',timeZone:'UTC'});}function iso(i){return dates[i].toISOString().slice(0,10);}function bucket(p){return Math.min(7,Math.max(0,d3.bisectRight(edges,p)-1));}function coord(xy){return `${Math.abs(xy[1]).toFixed(3)}° ${xy[1]>=0?'N':'S'} · ${Math.abs(xy[0]).toFixed(3)}° ${xy[0]>=0?'E':'W'}`;}function signed(v){return (v>=0?'+':'')+v.toFixed(2);}
function fmtDate(date){return new Date(date+'T00:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});}
// A land point that is not stored is below the threshold; its exact value is not published.
function selected(){const c=cellAt(state.point);if(!c||!field||!field.classes[c.index])return null;let lo=0,hi=field.index.length-1,value=null;while(lo<=hi){const mid=(lo+hi)>>1;if(field.index[mid]<c.index)lo=mid+1;else if(field.index[mid]>c.index)hi=mid-1;else{value=field.code[mid]/field.per;break;}}return {...c,value,below:value===null};}
function snapshot(){const c=selected();return {date:dates?iso(state.day):null,requestedPoint:state.point,covered:!!c,sampledGrid:c?.xy,probabilityPercent:c?.value??null,belowThreshold:c?.below??false,threshold:field?.threshold};}
function makeStats(c){const values=c.values,peak=d3.max(values),peakDay=values.indexOf(peak),count=Array.from(values).filter(p=>p>=state.threshold).length;return {mean:c.mean,climYear:c.climYear,anomaly:c.mean-c.climYear,peak,peakDay,count,monthly:months.map((m,i)=>{const vals=Array.from(values.slice(m.start,m.end)),above=vals.filter(p=>p>=state.threshold).length;return {...m,index:i,mean:d3.mean(vals),clim:c.clim[i],anomaly:d3.mean(vals)-c.clim[i],peak:d3.max(vals),n:vals.length,count:above,share:100*above/vals.length};})};}
function textMapValue(c){$('.y-map-value').replaceChildren();if(!c){$('.y-map-value').textContent=field?'No data':'…';return;}$('.y-map-value').append(document.createTextNode(c.below?`< ${field.threshold}`:c.value.toFixed(1)));const sm=document.createElement('small');sm.textContent='%';$('.y-map-value').append(sm);}
// Plate carrée: k is the number of pixels per degree. The map repeats in longitude and stops at the poles.
function view(){const map=$('.y-map'),w=map.clientWidth,h=map.clientHeight,k=Math.max(w/360,h/180,1e-9)*state.zoom,half=Math.min(90,h/(2*k));state.centre=[wrap(state.centre[0]),Math.max(half-90,Math.min(90-half,state.centre[1]))];const [cx,cy]=state.centre;return {w,h,k,project:xy=>[w/2+wrap(xy[0]-cx)*k,h/2-(xy[1]-cy)*k],invert:p=>[wrap(cx+(p[0]-w/2)/k),Math.max(-90,Math.min(90,cy-(p[1]-h/2)/k))]};}
function hatching(ctx,dpr){const tile=document.createElement('canvas');tile.width=tile.height=Math.round(6*dpr);const t=tile.getContext('2d');t.scale(tile.width/6,tile.width/6);t.strokeStyle='#b6c6c8';t.lineWidth=.55;for(const[x1,y1,x2,y2]of[[-1,1,1,-1],[0,6,6,0],[5,7,7,5]]){t.moveTo(x1,y1);t.lineTo(x2,y2);}t.stroke();return {dpr,fill:ctx.createPattern(tile,'repeat')};}
// Every pixel takes the colour of the grid box that contains its centre; values are never interpolated.
function paint(W,H,kd){raster??=document.createElement('canvas');if(raster.width!==W||raster.height!==H){raster.width=W;raster.height=H;}const ctx=raster.getContext('2d'),image=ctx.createImageData(W,H),out=new Uint32Array(image.data.buffer),g=archive.grid,classes=field.classes,[cx,cy]=state.centre,turn=new Float64Array(W);for(let x=0;x<W;x++)turn[x]=(((cx+(x+.5-W/2)/kd)%360)+360)%360/360;for(let y=0,p=0;y<H;y++){const lat=cy-(y+.5-H/2)/kd;if(lat>90||lat<-90){p+=W;continue;}const row=rowAt(lat),n=g.count[row],first=g.offset[row];for(let x=0;x<W;x++,p++){const col=(turn[x]*n+.5)|0;out[p]=palette[classes[first+(col<n?col:0)]];}}ctx.putImageData(image,0,0);return raster;}
function drawMap(){const v=view(),{w,h,k}=v;if(!w||!h)return;const canvas=$('.y-raster'),dpr=Math.min(3,window.devicePixelRatio||1),W=Math.round(w*dpr),H=Math.round(h*dpr),kd=k*dpr,[cx,cy]=state.centre,ctx=canvas.getContext('2d');if(canvas.width!==W||canvas.height!==H){canvas.width=W;canvas.height=H;}ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,W,H);
if(archive.world){const data=field?paint(W,H,kd):null,copies=[-360,0,360].filter(s=>W/2+(s+180-cx)*kd>0&&W/2+(s-180-cx)*kd<W),place=s=>ctx.setTransform(kd,0,0,kd,W/2+(s-cx)*kd,H/2+cy*kd),still=()=>ctx.setTransform(1,0,0,1,0,0);if(hatch?.dpr!==dpr)hatch=hatching(ctx,dpr);
// Land without a value is hatched and lakes are water; the field is drawn last, so that no value is hidden.
// Shores are drawn from a regional zoom: on the world map, small lakes would look like grid boxes.
for(const s of copies){ctx.save();place(s);ctx.clip(archive.world.land);still();ctx.fillStyle='#fafbf9';ctx.fillRect(0,0,W,H);if(data){ctx.fillStyle=hatch.fill;ctx.fillRect(0,0,W,H);}place(s);ctx.fillStyle='#e8eff0';ctx.fill(archive.world.lakes);still();if(data)ctx.drawImage(data,0,0);ctx.restore();}
const step=state.zoom<3?30:state.zoom<12?10:state.zoom<40?5:1,spanX=W/(2*kd),spanY=H/(2*kd);ctx.beginPath();for(let lon=Math.ceil((cx-spanX)/step)*step;lon<=cx+spanX;lon+=step){const x=Math.round(W/2+(lon-cx)*kd)+.5;ctx.moveTo(x,0);ctx.lineTo(x,H);}for(let lat=Math.max(-90,Math.ceil((cy-spanY)/step)*step);lat<=Math.min(90,cy+spanY);lat+=step){const y=Math.round(H/2-(lat-cy)*kd)+.5;ctx.moveTo(0,y);ctx.lineTo(W,y);}ctx.lineWidth=.5*dpr;ctx.strokeStyle='#c0cdd0';ctx.globalAlpha=.4;ctx.stroke();ctx.globalAlpha=1;
for(const s of copies){place(s);ctx.lineWidth=.7*dpr/kd;ctx.lineJoin='round';ctx.strokeStyle='#b8c8c9';ctx.stroke(archive.world.coast);if(state.zoom>=4)ctx.stroke(archive.world.lakes);}still();}
const svg=$('.y-geo');svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.replaceChildren();node('title',{},svg).textContent='Probability field; map selection shows the value of the selected grid box.';
if(state.zoom>=PLACE_ZOOM)for(const place of Object.values(places)){const p=v.project(place.xy);if(p[0]<10||p[0]>w-62||p[1]<40||p[1]>h-20)continue;node('circle',{cx:p[0],cy:p[1],r:2,fill:'#536d73'},svg);node('text',{x:p[0]+5,y:p[1]-5},svg).textContent=place.label;}
const c=selected(),p=v.project(c?c.xy:state.point);if(c&&c.width*k>=9)node('rect',{x:p[0]-c.width*k/2,y:h/2-(c.north-cy)*k,width:c.width*k,height:(c.north-c.south)*k,fill:'none',stroke:'#173c42','stroke-width':1.2},svg);if(p.every(Number.isFinite)){node('circle',{cx:p[0],cy:p[1],r:7,fill:'none',stroke:'#173c42','stroke-width':1.4},svg);node('circle',{cx:p[0],cy:p[1],r:3,fill:'#fff',stroke:'#173c42','stroke-width':1},svg);}
$('.y-map-detail').hidden=!state.clicked;$('.y-detail-name').textContent=state.place==='Coordinates'?'Selected grid box':`Near ${state.place}`;textMapValue(c);$('.y-detail-label').textContent=c?(c.below?'Daily probability · below the lowest interval':'Daily probability'):field?'Outside archive coverage':archive.problem?'Map not available':'Loading…';$('.y-cell').textContent=coord(c?c.xy:state.point);$('#year-plus').disabled=state.zoom>=MAX_ZOOM;$('#year-minus').disabled=state.zoom<=1;$('.y-map-status').hidden=!!field&&!archive.problem;$('.y-map-status').textContent=archive.problem||(archive.manifest?`Loading ${state.year}…`:'Loading map…');}
function plotBase(svg,w,h,ml=56,mb=36){svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.replaceChildren();const box={left:ml,right:w-12,top:24,bottom:h-mb};node('rect',{x:box.left,y:box.top,width:Math.max(1,box.right-box.left),height:box.bottom-box.top,fill:'none',stroke:'var(--y-line)','stroke-width':.7,'data-chart-frame':'true'},svg);return box;}
function showTooltip(html,x,y){const tip=$('.y-tooltip'),wrap=$('.y-chart-wrap');tip.innerHTML=html;tip.hidden=false;tip.style.left=Math.max(0,Math.min(wrap.clientWidth-195,x+12))+'px';tip.style.top=Math.max(0,y-74)+'px';}
function drawSeries(){const svg=$('.y-timeseries'),w=svg.clientWidth,h=svg.clientHeight;if(!currentCell||w<1)return;const b=plotBase(svg,w,h,52,38),values=currentCell.values;node('title',{},svg).textContent='Daily probability and an exploratory threshold. Click a day to show its map.';const ymax=d3.max([stats.peak,state.threshold])*1.12;seriesX=d3.scaleLinear().domain([0,dates.length]).range([b.left+1,b.right-1]);seriesY=d3.scaleLinear().domain([0,ymax]).nice(4).range([b.bottom-1,b.top+2]);const x=seriesX,y=seriesY;const maxY=y.domain()[1];
for(const t of y.ticks(4)){node('line',{x1:b.left,x2:b.right,y1:y(t),y2:y(t),stroke:'var(--y-line)','stroke-width':.6},svg);node('text',{x:b.left-8,y:y(t)+3,'text-anchor':'end'},svg).textContent=t;}
const tickMonths=w<420?[0,3,6,9]:Array.from({length:12},(_,i)=>i);for(const m of tickMonths)node('text',{x:x(months[m].start)+(m===0?2:0),y:h-20,'text-anchor':m===0?'start':'middle'},svg).textContent=months[m].name.slice(0,3);
node('text',{x:b.left,y:12,class:'y-axis-title'},svg).textContent='Probability (%)';node('text',{x:b.right,y:h-3,'text-anchor':'end',class:'y-axis-title'},svg).textContent=`${state.year} · UTC`;
if(state.mapMode==='monthly'){const m=months[state.month];node('rect',{x:x(m.start),y:b.top,width:x(m.end)-x(m.start),height:b.bottom-b.top,fill:'var(--y-series)',opacity:.055},svg);}
const data=Array.from(values,(p,d)=>({d,p}));data.push({d:dates.length,p:values[dates.length-1]});const area=d3.area().x(a=>x(a.d)).y0(y(0)).y1(a=>y(a.p)).curve(d3.curveStepAfter);node('path',{d:area(data),fill:'var(--y-series)',opacity:.08},svg);node('path',{d:d3.line().x(a=>x(a.d)).y(a=>y(a.p)).curve(d3.curveStepAfter)(data),fill:'none',stroke:'var(--y-series)','stroke-width':1.35},svg);
node('line',{x1:b.left,x2:b.right,y1:y(state.threshold),y2:y(state.threshold),stroke:'var(--y-sub)','stroke-width':.8,'stroke-dasharray':'2 4',opacity:.65},svg);const thresholdLabel=node('text',{x:b.right-4,y:y(state.threshold)-4,'text-anchor':'end'},svg);thresholdLabel.textContent=`${state.threshold}%`;thresholdLabel.style.paintOrder='stroke';thresholdLabel.style.stroke='var(--y-bg)';thresholdLabel.style.strokeWidth='3px';
const sx=x(state.day+.5);node('line',{x1:sx,x2:sx,y1:b.top,y2:b.bottom,stroke:'var(--y-series)','stroke-width':1,opacity:.55},svg);node('circle',{cx:sx,cy:y(values[state.day]),r:3.5,fill:'var(--y-bg)',stroke:'var(--y-series)','stroke-width':1.7},svg);
const guide=node('line',{x1:0,x2:0,y1:b.top,y2:b.bottom,stroke:'var(--y-sub)','stroke-width':1,visibility:'hidden','data-chart-hover-guide':'true'},svg);const marker=node('circle',{cx:0,cy:0,r:3,fill:'var(--y-series)',visibility:'hidden'},svg);const hit=node('rect',{x:b.left,y:b.top,width:b.right-b.left,height:b.bottom-b.top,fill:'transparent','data-chart-hit':'true'},svg);
function hitDay(e){const r=svg.getBoundingClientRect();return {px:Math.max(b.left,Math.min(b.right,e.clientX-r.left)),py:e.clientY-r.top,d:Math.max(0,Math.min(dates.length-1,Math.floor(x.invert(e.clientX-r.left))))};}
hit.onpointermove=e=>{const {px,py,d}=hitDay(e);guide.setAttribute('x1',px);guide.setAttribute('x2',px);guide.setAttribute('visibility','visible');marker.setAttribute('cx',px);marker.setAttribute('cy',y(values[d]));marker.setAttribute('visibility','visible');showTooltip(`<strong>${fmtDay(d)}</strong><br>Daily: ${values[d].toFixed(2)}%`,px,py);};hit.onpointerleave=()=>{guide.setAttribute('visibility','hidden');marker.setAttribute('visibility','hidden');$('.y-tooltip').hidden=true;};hit.onclick=e=>{setDay(hitDay(e).d,true);$('.y-tooltip').hidden=true;};
$('.y-chart-date').textContent=`${fmtDay(state.day)} · ${values[state.day].toFixed(1)}%`;
}

function drawMonths(){const svg=$('.y-month-chart'),w=svg.clientWidth,h=svg.clientHeight;if(!currentCell||!w)return;const b=plotBase(svg,w,h,52,36),metric=state.metric,vals=stats.monthly.map(m=>metric==='mean'?m.mean:metric==='anomaly'?m.anomaly:m.share),max=d3.max(vals),min=d3.min(vals),extent=metric==='anomaly'?[Math.min(0,min)*1.35,Math.max(.1,max)*1.4]:[0,Math.max(.5,max,...(metric==='mean'?currentCell.clim:[]))*1.25],x=d3.scaleBand().domain(d3.range(12)).range([b.left+4,b.right-4]).padding(.27),y=d3.scaleLinear().domain(extent).nice(4).range([b.bottom,b.top+8]);node('title',{},svg).textContent=`Monthly ${metric} for ${state.year}; climatology reference 1991–2020. Anomalies are percentage point differences.`;for(const t of y.ticks(4)){node('line',{x1:b.left,x2:b.right,y1:y(t),y2:y(t),stroke:'var(--y-line)','stroke-width':.6},svg);node('text',{x:b.left-8,y:y(t)+3,'text-anchor':'end'},svg).textContent=t;}
node('text',{x:b.left,y:12,class:'y-axis-title'},svg).textContent=metric==='mean'?'Mean daily probability (%)':metric==='anomaly'?'Difference from climatology (pp)':`Days ≥ ${state.threshold}% (% of month)`;
node('line',{x1:b.left,x2:b.right,y1:y(0),y2:y(0),stroke:'var(--y-sub)','stroke-width':.8},svg);
for(const m of stats.monthly){const v=vals[m.index],bar=node('rect',{x:x(m.index),y:y(Math.max(0,v)),width:x.bandwidth(),height:Math.abs(y(v)-y(0)),fill:metric==='anomaly'&&v<0?'var(--y-negative)':'var(--y-series)',opacity:metric==='anomaly'? .8:.52,'data-month':m.index,'data-value':v},svg);node('title',{},bar).textContent=`${m.name}: ${m.mean.toFixed(2)}%; reference ${m.clim.toFixed(2)}%; anomaly ${signed(m.anomaly)} pp`;
if(metric==='mean')node('line',{x1:x(m.index)-2,x2:x(m.index)+x.bandwidth()+2,y1:y(m.clim),y2:y(m.clim),stroke:'var(--y-sub)','stroke-width':2,'data-clim':m.clim},svg);
node('text',{x:x(m.index)+x.bandwidth()/2,y:h-18,'text-anchor':'middle'},svg).textContent=m.name.slice(0,w<500?1:3);
if(w>620)node('text',{x:x(m.index)+x.bandwidth()/2,y:v<0?y(v)+13:y(v)-5,'text-anchor':'middle'},svg).textContent=v.toFixed(1);
const target=node('rect',{x:x(m.index)-3,y:b.top,width:x.bandwidth()+6,height:b.bottom-b.top,fill:'transparent','data-month-hit':m.index},svg);node('title',{},target).textContent=`${m.name}: ${metric==='anomaly'?signed(v)+' pp':v.toFixed(2)+'%'}. Click for climatology map.`;target.onclick=()=>{pause();state.mapMode='monthly';state.month=m.index;render();save();};}
node('text',{x:b.right,y:h-2,'text-anchor':'end',class:'y-axis-title'},svg).textContent=`Month · ${state.year}`;const best=stats.monthly[vals.indexOf(max)],climBest=stats.monthly.reduce((a,m)=>m.clim>a.clim?m:a);$('.y-year-legend').textContent=metric==='mean'?String(state.year):metric==='anomaly'?'Above / below reference':`${state.year} · threshold exceedance`;$('.y-reference-legend').hidden=metric!=='mean';$('.y-month-legend i').style.background='var(--y-series)';$('.y-season-insight').textContent=metric==='mean'?`${climBest.name} has the highest reference mean (${climBest.clim.toFixed(2)}%); ${best.name} has the highest mean in ${state.year} (${best.mean.toFixed(2)}%).`:metric==='anomaly'?`${best.name} has the largest signed anomaly: ${signed(best.anomaly)} percentage points relative to 1991–2020.`:`${best.name}: ${best.count} of ${best.n} days at or above ${state.threshold}% (${best.share.toFixed(1)}%).`;}
// A location profile needs the daily series of a point; the manifest will list them once they are published.
function updateProfile(){const on=hasSeries();$('.y-profile').hidden=!on;all('[data-needs="series"]').forEach(el=>el.hidden=!on);if(!on){currentCell=null;stats=null;updateSupport();return;}const c=selected();currentCell=c;$('.y-profile-point').textContent=`Requested point · ${state.place==='Coordinates'?coord(state.point):state.place}`;$('.y-profile-sub').textContent=`${state.place==='Coordinates'?'':coord(state.point)+' · '}Sampled grid-box centre: ${c?coord(c.xy):'no coverage'}`;$('.y-analysis').hidden=!c;$('.y-empty').hidden=!!c;$('.y-coverage').textContent=c?`${state.year} · complete coverage`:'No archive coverage';all('[data-export]').forEach(b=>b.disabled=b.dataset.export!=='png'&&!c);$('.y-daily-title').textContent=`Daily probability · ${state.year}`;if(!c){stats=null;updateSupport();return;}stats=makeStats(c);$('.y-annual-mean').textContent=stats.mean.toFixed(2)+'%';$('.y-annual-anomaly').textContent=`${signed(stats.anomaly)} pp vs 1991–2020`;$('.y-annual-max').textContent=stats.peak.toFixed(1)+'%';$('.y-peak-date').textContent=fmtDay(stats.peakDay);$('.y-exceed-title').textContent=`Days at or above ${state.threshold}%`;$('.y-exceed-count').textContent=stats.count;$('.y-exceed-share').textContent=`${(100*stats.count/dates.length).toFixed(1)}% of available days`;$('.y-table-threshold').textContent=`Days ≥ ${state.threshold}%`;$('.y-month-table').replaceChildren();for(const m of stats.monthly){const tr=document.createElement('tr');for(const v of [m.name,m.n,m.mean.toFixed(2),m.clim.toFixed(2),signed(m.anomaly),m.peak.toFixed(1),m.count,m.share.toFixed(1)]){const td=document.createElement('td');td.textContent=v;tr.append(td);}$('.y-month-table').append(tr);}drawSeries();drawMonths();updateSupport();}
const skillText={reliability:'The preprint reports reliable probabilities below 10% at day 1 and below 2% at day 5 in its evaluated setting. These forecast findings do not establish calibration of this historical archive or every global location.',discrimination:'The paper evaluates discrimination using ROC and precision–recall curves across lead times. Proposed interactive view: choose product, lead time and validation region; inspect curves, sample counts and confidence intervals.',coverage:'The study uses impact reports over the contiguous United States and tests geographical generalisation. Show the actual validation region and period beside every score; do not assign a global skill score to each selected point.'};
function eventUrl(){const windowDays=Number($('#event-window').value),from=new Date(start+(state.day-windowDays)*DAY).toISOString().slice(0,10),to=new Date(start+(state.day+windowDays+1)*DAY).toISOString().slice(0,10);let place=state.place;if(place==='Coordinates'){const nearest=Object.values(places).map(p=>({p,d:Math.hypot((p.xy[0]-state.point[0])*Math.cos(state.point[1]*Math.PI/180),p.xy[1]-state.point[1])})).sort((a,b)=>a.d-b.d)[0];place=nearest.d<1?fullName(nearest.p):`${state.point[1].toFixed(3)}, ${state.point[0].toFixed(3)}`;}return 'https://www.google.com/search?q='+encodeURIComponent(`${place} flash flood flooding ${iso(state.day)} after:${from} before:${to}`);}
function updateSupport(){$('.y-skill-text').textContent=skillText[$('#skill-view').value];if(!archive.manifest)return;const c=selected();$('.y-quality-text').textContent=c?`${open.length} ${open.length===1?'day':'days'} published in ${state.year}. Grid: ${archive.grid.name}, about ${Math.round(archive.grid.spacing)} km. Grid-box centre: ${coord(c.xy)}. Values below ${archive.manifest.encoding.threshold}% are not published; others are rounded to ${archive.manifest.encoding.scale}. Model: ${archive.manifest.model_label}.`:'No probability sample at this point.';$('.y-credit-text').textContent=`${archive.manifest.attribution} Licence: CC BY 4.0. Inputs: ERA5 and ERA5-ecPoint; contains modified Copernicus Climate Change Service information.`;const url=eventUrl();$('#event-search').href=url;$('#chart-media').href=url;$('.y-event-label').textContent=`${state.place==='Coordinates'?coord(state.point):state.place} · ${fmtDay(state.day)} · ±${$('#event-window').value} days`;$('.y-download-context').textContent=hasSeries()?`Map: current view. Series and statistics: sampled grid box, ${state.year}. Reference: 1991–2020. Exports include coordinates, reference period and dataset provenance.`:'Map: current view, with its date and legend.';}
function save(){if(!archive.manifest)return;try{localStorage.setItem('poff-atlas-v2',JSON.stringify({...state,date:iso(state.day),concept:'atlas-archive'}));}catch{}}
function load(s){if(s?.concept!=='atlas-archive')return;if(typeof s.date==='string'&&available(s.date)){setYear(+s.date.slice(0,4));state.day=(Date.parse(s.date+'T00:00:00Z')-start)/DAY;state.month=dates[state.day].getUTCMonth();}if([1,3,5,10,25].includes(s.threshold))state.threshold=s.threshold;if(['mean','share','anomaly'].includes(s.metric))state.metric=s.metric;if(Array.isArray(s.point)&&s.point.length===2&&s.point.every(Number.isFinite)&&Math.abs(s.point[0])<=180&&Math.abs(s.point[1])<=90){if(s.point.some((v,i)=>v!==state.point[i]))state.clicked=false;state.point=s.point;$('#year-lat').value=String(s.point[1]);$('#year-lon').value=String(s.point[0]);state.place=typeof s.place==='string'?s.place.slice(0,150):'Coordinates';if(state.place==='Coordinates')state.method='coords';else $('#year-place').value=state.place;}}
function render(){root.style.colorScheme=state.appearance==='auto'?'light dark':state.appearance;root.style.setProperty('--y-radius',state.radius+'px');all('[data-find]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.find===state.method)));$('#year-name-form').hidden=state.method!=='name';$('#year-coord-form').hidden=state.method!=='coords';if(!archive.manifest){drawMap();return;}const whole=open.length===dates.length;$('#year-map-mode').value=state.mapMode;$('.y-date-field').hidden=state.mapMode!=='daily';$('.y-month-field').hidden=state.mapMode!=='monthly';$('.y-baseline-label').hidden=state.mapMode==='daily';$('#year-date').min=firstDate();$('#year-date').max=lastDate();$('#year-date').value=iso(state.day);$('#year-month').value=String(state.month);$('#year-day').max=String(open.length-1);$('#year-day').value=String(open.indexOf(state.day));$('#archive-year').value=String(state.year);$('#year-threshold').value=String(state.threshold);$('#year-month-metric').value=state.metric;$('.y-map-nav').hidden=archive.manifest.days<2;$('#year-play').hidden=$('#year-day').hidden=open.length<2;$('.y-range-labels').hidden=!whole;$('.y-range-date').textContent=fmtDay(state.day);$('.y-mode-label').textContent=state.mapMode==='daily'?'Daily · 24 h':'1991–2020';$('.y-valid').textContent=state.mapMode==='daily'?`${fmtDay(state.day)}, 00 UTC → ${new Date(start+(state.day+1)*DAY).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'})}, 00 UTC`:state.mapMode==='monthly'?`${months[state.month].name} climatology · 1991–2020`:'Year climatology · 1991–2020';$('.y-legend-quantity').textContent=state.mapMode==='daily'?'Daily occurrence probability (%)':'Climatological mean daily probability (%)';drawMap();updateProfile();}
// Show the selected day: at once when its year is loaded, otherwise once the year's file has been read.
function show(){const date=iso(state.day),year=state.year;$('.y-date-note').hidden=true;if(field?.date!==date){field=null;archive.problem='';const ready=archive.loaded.get(year);if(ready?.days)field=fieldOf(ready.days,date);else loadYear(year).then(days=>{archive.loaded.set(year,{days});if(iso(state.day)!==date||state.year!==year)return;field=fieldOf(days,date);render();},error=>{console.error(error);if(state.year!==year)return;archive.problem=`The maps of ${year} could not be read.`;render();});}render();}
function pause(){if(timer){clearInterval(timer);timer=null;}$('#year-play').textContent='Play year';}
function setDay(d,record=true){pause();state.day=nearest(Math.round(d));state.month=dates[state.day].getUTCMonth();state.mapMode='daily';show();if(record)save();}
// A place found by name or coordinates is brought into view; a point chosen on the map leaves the view as it is.
function choosePoint(xy,label,clicked=false){pause();state.point=xy;state.place=label;state.clicked=clicked;if(!clicked){state.centre=[...xy];state.zoom=Math.max(state.zoom,PLACE_ZOOM);}$('#year-lat').value=xy[1].toFixed(5);$('#year-lon').value=xy[0].toFixed(5);$('.y-error').hidden=true;hideSuggestions();render();save();}
function norm(s){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}function matches(){let q=norm($('#year-place').value.trim());q=({lisboa:'lisbon',sevilla:'seville'}[q]||q);return Object.entries(places).filter(([id,p])=>norm(fullName(p)).includes(q)).slice(0,6);}
function hideSuggestions(){$('#place-suggestions').hidden=true;$('#year-place').setAttribute('aria-expanded','false');}
function suggest(){const out=$('#place-suggestions');out.replaceChildren();const list=matches();for(const[id,p]of list){const b=document.createElement('button');b.type='button';b.dataset.place=id;const name=document.createElement('strong');name.textContent=fullName(p);const sub=document.createElement('small');sub.textContent=coord(p.xy);b.append(name,sub);b.onclick=()=>{$('#year-place').value=fullName(p);choosePoint(p.xy,fullName(p));};out.append(b);}out.hidden=!list.length;$('#year-place').setAttribute('aria-expanded',String(!!list.length));}
function findName(){const list=matches(),exact=list.filter(([id,p])=>norm(fullName(p))===norm($('#year-place').value.trim()));if(exact.length===1||list.length===1){const p=(exact[0]||list[0])[1];$('#year-place').value=fullName(p);choosePoint(p.xy,fullName(p));}else{suggest();$('.y-error').hidden=false;$('.y-error').textContent=list.length?'Choose a matching region and country.':'No matching place in this archive. Try a city or enter coordinates.';}}
all('[data-find]').forEach(b=>b.onclick=()=>{state.method=b.dataset.find;$('.y-error').hidden=true;hideSuggestions();render();});$('#year-place').oninput=suggest;$('#year-place').onfocus=suggest;$('#year-place').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();findName();}if(e.key==='Escape')hideSuggestions();};$('#year-name-form .y-search-row button').onclick=findName;
function findCoordinates(){const lat=$('#year-lat').value,lon=$('#year-lon').value;if(lat===''||lon===''||!Number.isFinite(+lat)||!Number.isFinite(+lon)||Math.abs(+lat)>90||Math.abs(+lon)>180){$('.y-error').hidden=false;$('.y-error').textContent='Latitude must be −90 to 90; longitude −180 to 180.';return;}choosePoint([+lon,+lat],'Coordinates');}$('#year-coord-form button').onclick=findCoordinates;for(const el of [$('#year-lat'),$('#year-lon')])el.onkeydown=e=>{if(e.key==='Enter')findCoordinates();};
$('#year-date').onchange=e=>{const date=e.target.value;if(!available(date)){$('.y-date-note').hidden=false;$('.y-date-note').textContent=date?`No map is published for ${fmtDate(date)}.`:'Choose a day.';e.target.value=iso(state.day);return;}if(+date.slice(0,4)!==state.year)setYear(+date.slice(0,4));setDay((Date.parse(date+'T00:00:00Z')-start)/DAY);};$('#year-day').oninput=e=>setDay(open[+e.target.value],false);$('#year-day').onchange=save;$('#archive-year').onchange=e=>{pause();const previous=dates[state.day],m=previous.getUTCMonth(),d=previous.getUTCDate();setYear(+e.target.value);const last=new Date(Date.UTC(state.year,m+1,0)).getUTCDate();setDay((Date.UTC(state.year,m,Math.min(d,last))-start)/DAY);};$('#year-map-mode').onchange=e=>{pause();state.mapMode=e.target.value;render();save();};$('#year-month').onchange=e=>{pause();state.month=+e.target.value;render();save();};$('#year-threshold').onchange=e=>{state.threshold=+e.target.value;updateProfile();save();};$('#year-month-metric').onchange=e=>{state.metric=e.target.value;drawMonths();save();};
$('#year-play').onclick=()=>{if(timer){pause();save();return;}if(state.day>=open.at(-1))state.day=open[0];state.mapMode='daily';show();$('#year-play').textContent='Pause';timer=setInterval(()=>{if(document.hidden){pause();return;}state.day=open[Math.min(open.length-1,open.indexOf(state.day)+1)];state.month=dates[state.day].getUTCMonth();show();if(state.day===open.at(-1)){pause();save();}},220);};
// Zooming keeps the anchor, a point of the map in pixels, over the same place.
function zoomTo(zoom,anchor){const before=anchor&&view().invert(anchor);state.zoom=Math.max(1,Math.min(MAX_ZOOM,zoom));if(anchor){const after=view().invert(anchor);state.centre=[state.centre[0]+wrap(before[0]-after[0]),state.centre[1]+before[1]-after[1]];}drawMap();}
$('#year-plus').onclick=()=>zoomTo(state.zoom*2);$('#year-minus').onclick=()=>zoomTo(state.zoom/2);$('#year-reset').onclick=()=>{state.zoom=HOME.zoom;state.centre=[...HOME.centre];drawMap();};$('.y-map-close').onclick=()=>{state.clicked=false;drawMap();};const svg=$('.y-geo');svg.onpointerdown=e=>{if(e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,centre:[...state.centre],moved:false};svg.setPointerCapture(e.pointerId);};svg.onpointermove=e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>4)drag.moved=true;if(drag.moved){const k=view().k;state.centre=[drag.centre[0]-dx/k,drag.centre[1]+dy/k];if(!raf)raf=requestAnimationFrame(()=>{raf=0;drawMap();});}};svg.onpointerup=e=>{if(!drag||e.pointerId!==drag.id)return;const moved=drag.moved;drag=null;if(svg.hasPointerCapture(e.pointerId))svg.releasePointerCapture(e.pointerId);if(!moved){const r=svg.getBoundingClientRect();choosePoint(view().invert([e.clientX-r.left,e.clientY-r.top]),'Coordinates',true);}};svg.onpointercancel=()=>{drag=null;};
// The page scrolls with the wheel; the map zooms with Ctrl or ⌘ held, which is also what a pinch on a trackpad sends.
svg.addEventListener('wheel',e=>{if(!e.ctrlKey&&!e.metaKey)return;e.preventDefault();const r=svg.getBoundingClientRect();zoomTo(state.zoom*Math.exp(-e.deltaY*.01),[e.clientX-r.left,e.clientY-r.top]);},{passive:false});
$('#skill-view').onchange=updateSupport;$('#event-window').onchange=updateSupport;$('#open-download').onclick=()=>{$('#download-panel').open=true;$('#download-panel').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});};
function csvEscape(v){return '"'+String(v).replaceAll('"','""')+'"';}
function csvRows(rows){return rows.map(r=>r.map(csvEscape).join(',')).join('\r\n')+'\r\n';}
function metadata(){const m=archive.manifest;return {data_status:m.title,model:m.model_label,run_sha256:m.run_sha256,licence:m.license,year:state.year,reference_period:'1991-2020',requested_latitude:state.point[1],requested_longitude:state.point[0],sampled_latitude:currentCell.xy[1],sampled_longitude:currentCell.xy[0],grid_cell_id:currentCell.index,threshold_percent:state.threshold};}
function dailyCSV(){const md=metadata(),keys=Object.keys(md);return csvRows([['date_utc','end_utc','probability_percent','monthly_climatology_percent','daily_minus_monthly_climatology_pp',...keys],...dates.map((date,d)=>{const m=date.getUTCMonth();return [iso(d),new Date(start+(d+1)*DAY).toISOString().slice(0,10),currentCell.values[d],currentCell.clim[m],currentCell.values[d]-currentCell.clim[m],...Object.values(md)];})]);}
function statisticsCSV(){const md=metadata(),keys=Object.keys(md);return csvRows([['period','valid_days','mean_probability_percent','climatology_percent','anomaly_pp','peak_probability_percent','days_at_or_above_threshold','share_percent',...keys],[state.year,dates.length,stats.mean,stats.climYear,stats.anomaly,stats.peak,stats.count,100*stats.count/dates.length,...Object.values(md)],...stats.monthly.map(m=>[`${state.year}-${String(m.index+1).padStart(2,'0')}`,m.n,m.mean,m.clim,m.anomaly,m.peak,m.count,m.share,...Object.values(md)])]);}
// NetCDF classic (CDF-1): fixed dimensions, XDR big-endian values, four-byte padding.
function netCDF(){const bytes=[],enc=new TextEncoder(),dims=[['time',dates.length],['month',12],['nv',2]],vars=[];const u32=n=>{bytes.push((n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255);},pad=()=>{while(bytes.length%4)bytes.push(0);},str=s=>{const a=enc.encode(String(s));u32(a.length);bytes.push(...a);pad();},attrs=o=>{const a=Object.entries(o);u32(a.length?12:0);u32(a.length);for(const[k,v]of a){str(k);u32(2);str(String(v));}};
function variable(name,dimensions,data,attributes={}){vars.push({name,dimensions,data:Array.from(data),attributes});}
variable('time',[0],dates.map((_,i)=>i),{units:`days since ${state.year}-01-01 00:00:00`,calendar:'proleptic_gregorian',bounds:'time_bounds'});variable('time_bounds',[0,2],dates.flatMap((_,i)=>[i,i+1]));variable('probability',[0],currentCell.values,{units:'percent',long_name:'Daily flash flood occurrence probability',coordinates:'latitude longitude'});variable('latitude',[],[currentCell.xy[1]],{units:'degrees_north'});variable('longitude',[],[currentCell.xy[0]],{units:'degrees_east'});variable('month',[1],d3.range(1,13));variable('monthly_climatology',[1],currentCell.clim,{units:'percent',reference_period:'1991-2020',long_name:'Mean daily probability by calendar month'});variable('monthly_anomaly',[1],stats.monthly.map(m=>m.anomaly),{units:'percentage_points',long_name:'Selected year monthly mean minus monthly climatology'});variable('year_climatology',[],[currentCell.climYear],{units:'percent',reference_period:'1991-2020'});
bytes.push(67,68,70,1);u32(0);u32(10);u32(dims.length);for(const[n,len]of dims){str(n);u32(len);}attrs({...metadata(),title:'Atlas location profile',licence:'CC BY 4.0',baseline_weighting:'All available reference days; day-weighted annual mean',source:archive.manifest.title,paper:'https://doi.org/10.5194/egusphere-2026-1591'});u32(11);u32(vars.length);for(const v of vars){str(v.name);u32(v.dimensions.length);v.dimensions.forEach(u32);attrs(v.attributes);u32(6);u32(v.data.length*8);v.offsetIndex=bytes.length;u32(0);}const headerSize=bytes.length,total=headerSize+vars.reduce((n,v)=>n+v.data.length*8,0),buffer=new ArrayBuffer(total),view=new DataView(buffer);new Uint8Array(buffer).set(bytes);let offset=headerSize;for(const v of vars){view.setUint32(v.offsetIndex,offset);for(const n of v.data){view.setFloat64(offset,n);offset+=8;}}return buffer;}
function exportFiles(){return {daily:dailyCSV(),statistics:statisticsCSV(),netcdf:Array.from(new Uint8Array(netCDF()))};}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.style.display='none';root.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),15000);}
async function mapPNG(){const original=$('.y-geo'),copy=original.cloneNode(true),width=original.clientWidth,height=original.clientHeight;copy.setAttribute('width',String(width));copy.setAttribute('height',String(height));copy.setAttribute('xmlns',ns);const sourceNodes=[original,...original.querySelectorAll('*')],clonedNodes=[copy,...copy.querySelectorAll('*')];sourceNodes.forEach((el,i)=>{const computed=getComputedStyle(el);for(const prop of ['fill','stroke','stroke-width','font','paint-order','letter-spacing'])clonedNodes[i].style.setProperty(prop,computed.getPropertyValue(prop));});const blob=new Blob([new XMLSerializer().serializeToString(copy)],{type:'image/svg+xml'}),url=URL.createObjectURL(blob);try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=Math.round(width*2);canvas.height=Math.round((height+152)*2);const ctx=canvas.getContext('2d');ctx.scale(2,2);ctx.fillStyle='#ffffff';ctx.fillRect(0,0,width,height+152);ctx.fillStyle='#19343d';ctx.font='15px Segoe UI';ctx.fillText('PoFF · '+(state.mapMode==='daily'?fmtDay(state.day):state.mapMode==='monthly'?months[state.month].name+' climatology · 1991–2020':'Year climatology · 1991–2020'),16,26);ctx.font='11px Segoe UI';ctx.fillText(`${archive.manifest?.title??'PoFF'} · Natural Earth geography`,16,45);ctx.fillStyle='#e8eff0';ctx.fillRect(0,58,width,height);ctx.drawImage($('.y-raster'),0,58,width,height);ctx.drawImage(image,0,58,width,height);ctx.fillStyle='#19343d';ctx.fillText(state.mapMode==='daily'?'Daily occurrence probability (%)':'Climatological mean daily probability (%)',16,height+80);const left=16,span=(width-32)/8;for(let i=0;i<8;i++){ctx.fillStyle=colours[i];ctx.fillRect(left+i*span,height+90,span,9);}ctx.fillStyle='#536b72';ctx.font='10px Segoe UI';for(let i=0;i<=8;i++){ctx.textAlign=i===8?'right':i===0?'left':'center';ctx.fillText(String(edges[i]),left+i*span,height+115);}ctx.textAlign='left';ctx.fillText(`${archive.manifest?.attribution??''} CC BY 4.0. Contains modified Copernicus Climate Change Service information.`,16,height+139,width-32);const png=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!png)throw Error('PNG could not be created');return png;}finally{URL.revokeObjectURL(url);}}
all('[data-export]').forEach(button=>button.onclick=async()=>{const kind=button.dataset.export,status=$('.y-export-status');try{status.textContent='Preparing download…';let blob,name;const prefix=`poff-${state.year}`;if(kind==='png'){blob=await mapPNG();name=`${prefix}-${state.mapMode}-${state.mapMode==='daily'?iso(state.day):state.mapMode==='monthly'?String(state.month+1).padStart(2,'0'):'1991-2020'}.png`;}else{if(!currentCell)throw Error('Select a grid box with data.');if(kind==='nc'){blob=new Blob([netCDF()],{type:'application/x-netcdf'});name=prefix+'-location.nc';}else{blob=new Blob([kind==='stats'?statisticsCSV():dailyCSV()],{type:'text/csv;charset=utf-8'});name=prefix+(kind==='stats'?'-statistics.csv':'-daily.csv');}}download(blob,name);status.textContent=`Downloaded ${name}.`;}catch(e){status.textContent='Download failed: '+e.message;}});

// The page opens on the most recent published day.
function describe(){const m=archive.manifest,note=$('.y-sidebar-note'),first=firstDate(),last=lastDate(),lines=[`Archive · ${first===last?fmtDate(first):fmtDate(first)+' – '+fmtDate(last)}`,`${m.days.toLocaleString('en-GB')} ${m.days===1?'day':'days'} published`,`Grid · ${archive.grid.name}, about ${Math.round(archive.grid.spacing)} km`];note.replaceChildren();lines.forEach((line,i)=>{if(i)note.append(document.createElement('br'));note.append(line);});$('#archive-year').replaceChildren(...[...archive.years.keys()].map(y=>{const opt=document.createElement('option');opt.textContent=String(y);return opt;}));for(const m of months){const opt=document.createElement('option');opt.value=String(months.indexOf(m));opt.textContent=m.name;$('#year-month').append(opt);}
// Climatology maps are offered once the manifest lists a reference period.
$('#year-map-mode').closest('.y-field').hidden=!m.climatology;}
setupSite();render();new ResizeObserver(()=>{drawMap();drawSeries();drawMonths();}).observe(root);
openArchive().then(()=>{const last=lastDate();setYear(+last.slice(0,4));state.day=open.at(-1);state.month=dates[state.day].getUTCMonth();describe();try{load(JSON.parse(localStorage.getItem('poff-atlas-v2')));}catch{}show();},error=>{console.error(error);archive.problem=typeof DecompressionStream==='function'?'The archive could not be read. Please try again later.':'This browser cannot read the archive. Please update it.';render();});
root.atlasSnapshot=()=>({state:{...state},...snapshot(),published:archive.manifest?.days??0,ready:!!field,problem:archive.problem});
})();
